<<<<<<< HEAD
mocean_page:
    resource: "@MoceanMoceanBundle/Resources/config/routing.yml"
    prefix:   /

raresrares:
    resource: "@raresraresBundle/Resources/config/routing.yml"
=======
ampoitan_nicu:
    resource: "@AmpoitanNicuBundle/Resources/config/routing.yml"
>>>>>>> 1c29bdff33a7a86f633a6b910c3d46d75245ffd2
    prefix:   /

andrei_personal_page:
    resource: "@AndreiPersonalPageBundle/Resources/config/routing.yml"
    prefix:   /

sonia_page:
    resource: "@SoniaPageBundle/Resources/config/routing.yml"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

angelescuangelescu:
    resource: "@AngelescuangelescuBundle/Resources/config/routing.yml"
    prefix:   /

tudor_pag_pers:
    resource: "@TudorPagPersBundle/Resources/config/routing.yml"
    prefix:   /
a_ciungan_blog:
    resource: "@ACiunganBlogBundle/Resources/config/routing.yml"
    prefix:   /

daniel_my_page:
    resource: "@DanielMyPageBundle/Resources/config/routing.yml"
    prefix:   /

